version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=test
      - DATABASE_URL=postgresql://testuser:testpass@db:5432/ecommerce_test
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=ecommerce_test
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    
  selenium-hub:
    image: selenium/hub:4.0.0
    ports:
      - "4444:4444"
    environment:
      - GRID_MAX_SESSION=5
      - GRID_BROWSER_TIMEOUT=300
      - GRID_TIMEOUT=300
    
  selenium-chrome:
    image: selenium/node-chrome:4.0.0
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - NODE_MAX_INSTANCES=3
      - NODE_MAX_SESSION=3
    volumes:
      - /dev/shm:/dev/shm
    
  selenium-firefox:
    image: selenium/node-firefox:4.0.0
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - NODE_MAX_INSTANCES=3
      - NODE_MAX_SESSION=3
    volumes:
      - /dev/shm:/dev/shm

volumes:
  postgres_data: